title: Curso Programación I
author: Joshua Bernal & Ricardo Ortega
logo: content/imgs/logo.png
copyright: "2023"

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/BioAITeamLearning/prog1-2023-02-ucaldas
  branch: master

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - html_admonition
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

sphinx:
  config:
    language: es